version: "3.7"

services:
  app:
    build: .
    ports:
      - 3000:4000
    environment:
      MONGODB_CONNECTION_URL: mongodb://secretUserName:secretPassword@mongo:27017/

  mongo:
    image: mongo
    volumes:
      - /Users/omer/Desktop/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: secretUserName
      MONGO_INITDB_ROOT_PASSWORD: secretPassword

volumes:
  mongo-data:
